import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CDS Tech Support | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Tech Support for <Link href="https://www.carolinaday.org/"><a>CDS</a></Link>!
        </h1>

        <h1 className={styles.description}>
          Which of the following best describes you?
        </h1>

        <div className={styles.grid}>
          <a href="/parent" className={styles.card}>
            <h2>Parent</h2>
          </a>

          <a href="/teacher" className={styles.card}>
            <h2>Teacher</h2>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        Propery of Carolina Day School. All rights reserved.
      </footer>
    </div>
  )
}
